name: Update SixDeadBeefs/kali-ctf-core Repository
on:
  push:
    paths:
      - 'docker/core/Dockerfile'
      - 'docker/core/aliases'
jobs:
  Dockerhub-Update:
    name: SixDeadBeefs/kali-ctf-core Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}        
      - name: Cache 
        uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: docker/core/
          push: true
          tags: sixdeadbeefs/kali-ctf-core:latest
